spring:
  application:
    name: agrocore-backend

  # Base de Datos
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/agrocore_db?sslmode=disable
    username: agrocore_user
    password: agrocore_password
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate # Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway (Control de versiones de BD)
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Kafka
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: agrocore-telemetry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "co.edu.udea.agrocore.backend.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: co.edu.udea.agrocore.backend.infrastructure.adapter.in.messaging.dto.TelemetryEvent

# Configuracion AgroCore
agrocore:
  kafka:
    topics:
      telemetry: agrocore.telemetry.readings.v1
      telemetry-dlq: agrocore.telemetry.readings.v1.dlq
    partitions: 3
    replication-factor: 1
